version: "3.8"

services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    command: redis-server --requirepass pass
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - innoloft_network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: innoloft_db
      MYSQL_USER: innoloft
      MYSQL_PASSWORD: innoloftpass
    ports:
      - "3306:3306"
    networks:
      - innoloft_network

  api:
    image: innoloft
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=innoloft_db;User=innoloft;Password=innoloftpass"
      RedisConfig__Host: "redis-server:6379"
      RedisConfig__Password: "pass"
      RedisConfig__DB: 1
    ports:
      - 5177:5177
    networks:
      - innoloft_network
    depends_on:
      - mysql
      - redis-server

networks:
  innoloft_network:
    driver: bridge
